<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOySOrjK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOySOrjK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOySOrjK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOySOrjK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOySOrjK\App_KernelDevDebugContainer([
    'container.build_hash' => 'OySOrjK',
    'container.build_id' => '621ec583',
    'container.build_time' => 1577464278,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOySOrjK');
